# Generated by Django 4.2.23 on 2026-01-20 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_timestap",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=12, verbose_name="Номер телефона"),
                ),
                (
                    "requires_delivery",
                    models.BooleanField(
                        default=False, verbose_name="Требуется доставка"
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Адрес доставки"
                    ),
                ),
                (
                    "payment_on_get",
                    models.BooleanField(
                        default=False, verbose_name="Оплата при получении"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Оплачен")),
                (
                    "status",
                    models.CharField(
                        default="В обработке", max_length=50, verbose_name="Статус"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "orders",
            },
        ),
    ]
