# Generated by Django 4.2.23 on 2025-09-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_category_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("id",),
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
